name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 5 * * *' # daily at 05:00 UTC
  workflow_dispatch: {}

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (no scripts)
        run: |
          npm ci --ignore-scripts

      - name: Run keep-alive script
        env:
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
        run: node scripts/keepalive.mjs

